- src/GoUtil.ts
It's quite noisy in the console, gets in the way of other debug.
> Get rid of scaling log message

- src/GoEngine.ts
- src/GobanCore.ts
Fixes #30 
This fixes some type issues that I found when cleaning up GameInfoModal (PR incoming)
- GoEnginePlayerEntry.pro changed to boolean
- GoEngineConfig.winner added
> Some more typings

- src/AIReview.ts
This function is a little smarter than compute worst moves as it determines whether to use score on its own, and also filters out non-blunders.
> add getWorstMoves

- .github/workflows/main.yml
- package.json
- prettier.config.js
- src/AIReview.ts
- src/AdHocFormat.ts
- src/GoConditionalMove.ts
- src/GoEngine.ts
- src/GoMath.ts
- src/GoStoneGroup.ts
- src/GoTheme.ts
- src/GoThemes.ts
- src/GoUtil.ts
- src/GobanCanvas.ts
- src/GobanCore.ts
- src/GobanError.ts
- src/JGOF.ts
- src/MoveTree.ts
- src/ScoreEstimator.ts
- src/TypedEventEmitter.ts
- src/goban.ts
- src/test.tsx
- src/themes/board_plain.ts
- src/themes/board_woods.ts
- src/themes/disc.ts
- src/themes/rendered_stones.ts
- src/translate.ts
- yarn.lock
- Add Prettier
- Add GitHub workflow check
- Run Prettier (twice)
- Prettier had trouble over a bit of code with an inline comment and needed two passes.  Issue appears to be transient and harmless.
Note: I didn't bother removing formatting rules from TSLint since there wasn't a CI check and lint already fails.
> Add prettier

- src/GoEngine.ts
- src/GobanCanvas.ts
- src/GobanCore.ts
... in its own commit, in case it breaks something.
> Changed == to === (and removed semicolons)

- src/ScoreEstimator.ts
Before/after:
This should also fix the issue with wrong Japanese handicap scoring:
https://github.com/online-go/online-go.com/issues/1610
One possible issue is that in games with no territory estimated, there's nothing at all marked on the board:
> In basic score estimator, under Japanese rules, do not count points for stones, add points for captures

- package.json
- src/GoEngine.ts
- src/GobanCanvas.ts
- src/GobanCore.ts
- src/JGOF.ts
This PR adds support for player_update events from the server, and support for rengo_casual_mode flag.
> Process player updates

- package.json
- src/GoEngine.ts
- src/GobanCanvas.ts
- src/GobanCore.ts
... so that we have a single way of asking if someone is a participant.
> Add engine.isParticipant()

- package.json
- src/GoEngine.ts
- src/GobanCanvas.ts
- src/GobanCore.ts
This branch is the staging area for adding support for clients to send what their clock state was when the made a move, allowing for playing down to the wire even when you have horrible ping times.
> Reliable clock

- src/GoEngine.ts
- src/GobanCanvas.ts
- src/GobanCore.ts
- src/TypedEventEmitter.ts
This branch tracks some changes needed for the `Game.tsx` refactor going on in the online-go.com repo
> Add numerous events to notify subscribers when certain fields change

- README.md
So turned out husky was already added to the project, I just hadn't installed it yet 🤦‍♂️ I figure it'll help new contributors to add it to the README
> Add husky step to the README

- src/GobanCanvas.ts
- src/GobanCore.ts
So I was looking into `onTap()`, and I noticed there was this `"pattern search"` mode.  A couple reasons why I think it might be okay to remove it:
- `pattern_search_color` only ever gets set to `0`, so some of this code is flat-out dead
- The other repos don't have any mentions of "pattern search"
I could totally be missing something, but if not, I think this is a nice opportunity to simplify the Goban code!
> Remove pattern search mode

- package.json
- src/GoEngine.ts
- src/GobanCore.ts
This should fix the issue identified in https://github.com/online-go/online-go.com/issues/2086
> Fix slow stone removal group toggling

- src/GobanSocket.ts
- src/protocol/ClientToAIServer.ts
- src/protocol/ClientToServer.ts
See https://github.com/online-go/goban/pull/116#discussion_r1141649945
This should help with the type hints in GobanSocket where the "authenticate" and "net/ping" messages are expected.
> Add base class for ClientToServer events.

- src/GobanCanvas.ts
fixes https://github.com/online-go/goban/issues/121
> Issue 121 - blur active input element on goban touch event

- src/GobanSocket.ts
(and rename the internal timer variable to avoid confusion)
> Add ping_interval option to GobanSocket.options 

- src/GobanSocket.ts
Gives GobanSocket a ping timeout event.
> Ping timeout event

- src/GoEngine.ts
Enables the rank difference to be displayed in the web-client.
> Declare new handicap_rank_difference field

- src/GobanCore.ts
- src/themes/board_plain.ts
- src/themes/board_woods.ts
- src/themes/disc.ts
- src/themes/image_stones.ts
- src/translate.ts
In support of https://github.com/online-go/online-go.com/issues/2481
> Support for supplying a url for stone images via Goban hook

- src/GobanCanvas.ts
… so it's easier to see what it can do.
I'm not married to this idea, but it seems like it should be helpful?
> Add an interface declaration for GobanCanvas

- src/GobanCanvas.ts
- src/GobanCore.ts
… when it's opacity we're dealing with.
We don't have to do this, but https://github.com/online-go/online-go.com/pull/2533 needs it.
> Change terminology from "transparency" to "opacity" 

- .vscode/cspell.json
- src/GoTheme.ts
- src/Goban.styl
- src/GobanCanvas.ts
- src/GobanCore.ts
- src/GobanSVG.ts
- src/__tests__/GobanSVG.test.ts
- src/canvas_utils.ts
- src/goban.ts
- src/test.tsx
- src/themes/image_stones.ts
- src/themes/plain_stones.ts
- src/themes/rendered_stones.ts
- test/index.html
- tsconfig.json
This adds an SVG based renderer for our goban.
> Goban SVG renderer

- webpack.config.js
... so that people know this cool thing exists.
> Add a dev server banner message

- src/engine/protocol/ServerToClient.ts
Support with type updates for https://github.com/online-go/online-go.com/pull/2977
> Tweak ServerToClient definitions to match django refactor

- src/engine/formats/JGOF.ts
Include playouts, visits optionally in JGOFAIreview
> Include playouts, visits optionally in JGOFAIreview

- src/engine/formats/JGOF.ts
So we can send it in there, and use it in AI detection page
> add cheat_detection field to JGOFAIReview

- src/Goban/CanvasRenderer.ts
- src/Goban/Goban.ts
- src/Goban/SVGRenderer.ts
- src/GobanBase.ts
The goal of this branch is to add the capability of having an evaluation bar to the left of the board
> Evaluation bar
