online-go/goban

src/GobanCanvas.ts
As a moderator, I need this all the time, so that when I get called to "timewasting" reports I can see at a glance where the reporter first passed, instead of trawling through the game to see where timewasting started.
I'd thought to dim the stone which is a pass, but that's a much deeper change (requiring modification to placeBlackStone, placeWhiteStone, so I went with this lightweight version.
=> Show a pass as a '.' in the "move number" in the move tree

src/GoTheme.ts, src/GobanCore.ts, src/themes/board_plain.ts
**WARNING: This PR is co-dependant with [this one](https://github.com/online-go/online-go.com/pull/1179) on online-go.com**
---
The basic idea is to allow users to style their goban with a custom image in the form of supplying a link to an external picture. 
- I have changed the look of the plain board preview in the selector, to more intuitively represent the cutomizable nature
- Upon selecting the custom option an input form appears together with the color selectors, once the text is replaced with an image link, it will automatically update the board background. 
- in the future I was thinking of creating a similar option for the stones, together with two buttons allowing for playing one-color-go and blind-go easily. Let me know what you think about that.
---
Please note, this is my …
=> External goban image 

src/GoEngine.ts
start-time and end-time are in the GoEngineConfig we get from the server, so declaration needed
=> Added start-time and end-time to GoEngineConfig declaration

src/GobanCore.ts
When score estimation mode is exited during a review the mode is now set to "analyze" and the board is reset to the current move (as opposed to the original empty board position, which is the "last official move" when in a review).
This diff will have no user facing impact until the PR which adds score estimation in reviews to `online-go.com` is merged: https://github.com/online-go/online-go.com/pull/1272
**Side question for the developers**: Why does "Back to Game" in score estimation (for a real game, not a review) return to the last official move as opposed to the board position that the score was estimating (e.g. if the player had moved back in the move tree and then run score estimation)? I can change this behavior so that `esc` and "Back to Game" return to "current move" as opposed …
=> Handle reviews properly in setScoringMode

src/GobanCore.ts
Previously when pressing "Back to Game" (or `esc`) in score estimator mode you would be taken back to the last official move and placed in the `play` mode. This change returns you to the previous board mode and position.
=> Return to previous mode and board position when exiting score estimator

src/GobanCore.ts
Fixes these issues (will need to manually close these since they're in the `online-go` repo):
https://github.com/online-go/online-go.com/issues/1290
https://github.com/online-go/online-go.com/issues/1291
This fixes the bugs by doing two things:
1. Return to `play` mode and jump to official move unless we were previously in `analyze` or `conditional` mode (i.e. only allow this "feature" where we think it's safe, rather than allowing for exposing latent bugs when returning to different modes which was the cause of the above issues). This should fix the "staged submit move" by just jumping back to the official move.
2. Allow conditional mode even if it's the current players turn if we were previously in estimate score mode.
=> Fix stop estimating score

src/GobanCanvas.ts
Sentry keeps getting "stone_already_placed_here" reports, and they appear in the console.
I don't think there's any reason for this: the goban raises this exception to bomb out of onClick processing, but it's not really an error.
this.errorHandler() already has a check to ignore this exception, but unfortunately at the level that this.errorHandler() is called there is another place (console.info(e) that is causing it to be reported.  Hence the need for this, I think.
=> Don't issue error messages on "stone_already_placed_here" exception

src/GoEngine.ts, src/GobanCanvas.ts
Fixes the following bugs:
- Ko's were not respected in puzzles if they occured within the first 3 moves. This is because pre-placed stones in the puzzle do not count towards the move count, which means Ko's can occur within the first 3 moves of the puzzle which is impossible in real games/reviews. Fixed this by ignoring the `this.cur_move.move_number > 2` check if we are in puzzle mode.
- Fixed Goban error message disappearing as soon as it appears on mobile due to "phantom click". Prevented this by delaying the message from rendering by 100ms, allowing the "phantom click" to occur before the `click` event handler has been registered for the message.
This screen capture shows both bugs that were fixed in this PR: https://streamable.com/x3qwqf
=> Fixed Goban error message on mobile and puzzle ko bug

src/GobanCanvas.ts, src/GobanCore.ts
This change allows for a custom variation stone transparency level. It will have no effect until the corresponding OGS PR merges: https://github.com/online-go/online-go.com/pull/1317
=> Added variation stone transparency support to Goban

src/GobanCore.ts
After a long time trying to figure out why I couldn't place stones in the test, I finally realized that `GobanCore`'s constructor didn't do anything with `config.mode`.  There was also inconsistent typing that I decided to take care of regarding `GobanCore.mode` and `GobanConfig.mode`.  Once I tightened up the types, it was revealed that `GobanCore.has_new_official_move` isn't used, so I removed it.
This change should not affect online-go.com as it is using Goban.setMode() in most places to set the mode, but I was not able to verify this.  Is there a way to run dev.beta.online-go.com using a dev version of Goban?
=> Respect config.mode in constructor

src/GoEngine.ts
See discussion here: https://forums.online-go.com/t/illegal-ko-move/32389/4
Text copied from post:
> From testing it out it doesn't seem like anything goes wrong (or explodes), but I haven't tried too many edge cases (not sure what they would be). This logic seems do the "correct" thing (return false) when evaluated on the first move (i.e. there is no previous move): `this.boardStatesAreTheSame(current_state, this.cur_move.index(-1).state)`
> 
> However, this doesn't fully solve the forked game issue. As we check for ko by determining if the previous board state is the same, a game without an earlier move tree will never find a ko on the first move even though this is possible in a forked game (e.g. forking this game: https://beta.online-go.com/game/9717).
> 
> If we copied move history, …
=> Removed ko check that is likely unnecessary

src/GobanCanvas.ts, src/GobanCore.ts
Some people would like [a visual indication if they have received an undo request](https://forums.online-go.com/t/wish-better-noticeable-undo-requests/964/70?u=eugene).
This change provides a preference setting to indicate that this is desired, and puts a '?' on the latest move if there is an undo request on it.
It does _not_ try to colour the '?' red as some requested, because that is an absolute can of worms - the 'standard' black stone has a white highlight on it, which causes a red question mark to look bad-contrast.    Not to mention what happens with themes.
This implementation assumes that the colour that has been selected for other marks to be drawn on the stones is the right one.
=> Show '?' on latest move if there is an undo request for it.

src/GobanCore.ts
Note: I checked that not-assigning to undefined does result in the variable being `=== undefined`, just as if it were assigned.
=> Fix semicolons and unnecessary assignment to undefined - make tslint happy

src/GoEngine.ts
Fixes #26
Before:
After:
Another benefit that you can see from the screenshot is that we properly recognize that territory shouldn't be scored since it's a "timeout".
Opened new issue to track the server side change still required to fix the SGF library page showing "?" (which actually looks like this should fix as well, so hopefully a noop after deploy): https://github.com/online-go/online-go.com/issues/1348
=> Parsed outcome from SGF on load if missing

src/GoEngine.ts, src/GobanCore.ts
Fixes #27 
This change uses the score estimator to find dead stones in SGF uploaded games, since they don't include `gamedata.removed` (even if the SGF did include dead stones). This makes the final territory marking more accurate.
In the resignation case, there was just a small bug where `outcome: resign` instead of `outcome: Resignation` in the game data, causing it to improperly render marks on the board for SGF games that resulted in resignation.
Both of these changes should now make SGF final board state rendering much closer to their native OGS game counterparts.
Before (when game ends in resignation):
After (when game ends in resignation):
Before (when game ends with score):
After (when game ends with score):
Once OGS server-side supports parsing dead stones from SGFs the …
=> Fix sgf dead stones

src/GoEngine.ts
Game data has `outcome: 'r'` for these SGF uploaded games which I've never seen before, leading to incorrectly marking territory:
https://online-go.com/game/30411889
https://online-go.com/game/28824220
The SGFs seem to be properly formatted, so not sure what's going wrong in the server side parser. @anoek Did something recently change? I've never seen `r` before as an outcome.
This fixes the issue by handling the new outcome and correcting it to a recognized outcome type so that territory isn't marked.
Before (1):
After (1):
Before (2):
After (2):
=> Fixed unrecognized resignation outcome string

src/themes/board_plain.ts, src/themes/board_woods.ts
[Issue was the AI evaluation text was difficult to read on dark boards](https://github.com/online-go/online-go.com/issues/1491). The fix was:
* Granite board: white AI evaluation text.
* Night board: white AI evaluation text.
* HNE night: white AI evaluation text.
* HNE: black AI evaluation text (white looks slightly worse with the bright light blue board, black stands out better in the blue circle thingy).
See changes below:
=> Goban 2021.10.10 issue #1491 on online-go.com - Unreadable AI evaluation text when using dark theme boards #1491

src/GobanCore.ts
I noticed that It is easy to misclick if the cursor is at the very edge of the "ghost" stone.
Apparently this also happens to others, e.g. see https://youtu.be/nNxD47Bfhhw?t=1303
This pull request adds a small "deadzone" between intersections, in which clicks have no effect.
=> Add a small deadzone in between intersections to prevent misclicks

src/AIReview.ts, src/GoEngine.ts, src/GobanCore.ts, src/MoveTree.ts
- Add ability to use score as the metric for "Key Moves"
- I did it with an additional parameter to allow for score instead of win rate.  Perhaps that puts too much onus on the API clients?  Let me know if I should move more logic into this function.
- Change type definition for SetMarks (I don't think it's actually meant to handle a MarkInterface proper)
=> AIReview updates

tslint.json
I don't know if this is all of them, but this is a quick fix for some prettier conflicts @GreenAsJade bumped into.
Long-term plan is to nix TSLint in favor of ESLint, hence why not a more thorough investigation of prettier compatibility.
=> Take out TSLint rules that look like they do formatting.

webpack.config.js
I'm not sure if this is the correct solution (I'm kind of getting my feet wet with webpack), but I'll try to explain the problem and proposed solution below.
When I try to instantiate a `Goban` in tests, I get the following error:
```
goban_1.Goban is not a constructor
```
When I log the value of `Goban`, I get `undefined`, and if I try to log the `goban` module itself, it is an empty object.
The reason this happens is that webpack is configured by default to be "imported" via the `script` tag.  However, jest doesn't have an html file where we can load scripts.
This PR has webpack build the module as [UMD](https://github.com/umdjs/umd).  That means that it can be imported as `CommonJS` in addition to the `script` way.
- Does this mess with any existing deployment flows?
- Overhead (if I'm …
=> Generate a UMD module with webpack.

src/GobanCore.ts
There was a comment here saying that `score_estimate` is a `ScoreEstimator`.  Looking at the code, this seems to be appropriate.
This introduces a minor type error in the React repo that is fixed with https://github.com/online-go/online-go.com/pull/1841
=> Add type for score_estimate.

src/GobanCore.ts
There are two problems with the current way of toggling coordinates:
1) top, bottom, left, and right must be set even though the caller usually wants to set "bottom-right", "all", "top-left" etc.
2) Square sizes are not recalculated and a rerender is not triggered by setting any of the coordinate labels.
The call-site (in the React repo) will change in the following way:
```diff
- goban.current.draw_top_labels =
-     label_position === "all" || label_position.indexOf("top") >= 0;
- goban.current.draw_left_labels =
-     label_position === "all" || label_position.indexOf("left") >= 0;
- goban.current.draw_right_labels =
-     label_position === "all" || label_position.indexOf("right") >= 0;
- goban.current.draw_bottom_labels =
-     label_position === "all" || …
```
=> add setCoordinates function that triggers a rerender

src/GobanCore.ts
Bug: https://forums.online-go.com/t/new-bug-for-smaller-boards/43299/2
Error arose in https://github.com/online-go/online-go.com/pull/1873
I think there were ~two~ issues about the "load" function:
- square size was not changed if config did not specify a display size.
- Naturally socket does not send a display size with the "game_data" event
- this.display_size may be set prior to the load event, in which case we will still need to recalculate the square size
- ~redraw not triggered if engine was previously undefined.~ I read the code wrong, redraw logic was already correct.
=> Fix small boards issue

src/GoEngine.ts, src/MoveTree.ts
MA is the officially supported property for marking points with an X: https://www.red-bean.com/sgf/properties.html#MA
This pull request aims to maintain backwards compatibility.  Newly exported SGFs will use the MA field, but the XX field will still be recognized when reading a "legacy" SGF in.
https://forums.online-go.com/t/ogs-seems-to-not-respect-the-sgf-standard-with-the-x-marking/43361/2
=> Use MA instead of XX for SGF exports.

.eslintrc.js, .github/workflows/main.yml, jest.config.ts, package.json, src/__tests__/GoMath.test.ts, yarn.lock
I believe getting proper test coverage would be one step towards making it more approachable by giving confidence that changes do not have unintended consequences.  This is especially important because downstream users of Goban may not be immediately apparent (the react repo, the backend repo).  Tests provide a way to document use cases directly and in an automated fashion in this repo.
It's worth noting that there are an abundance test frameworks to choose from (example alternatives: Jasmine, Mocha). I just chose Jest because we are already using it in the React repo.
The workflow checks two things: test correctness and coverage.  I've got about 60% (by lines) of GoMath covered to show how testing might look in practice.  This translates to about 2.5% of the codebase. …
=> Add test framework (Jest)

src/GobanCore.ts
Changes:
- Set the audio clock color to the "opposite" color of the last official move instead of `engine.colorToMove()`.
Fixes https://github.com/online-go/online-go.com/issues/1231 and https://github.com/online-go/online-go.com/issues/1723.
=> Fix audio-clock color

src/GoEngine.ts
Fixes https://github.com/online-go/online-go.com/issues/2016
Changes: don't enable analysis if the player is a rengo participant
=> Fix disable_analysis setting in rengo games

README.md, src/GoMath.ts, src/GobanCanvas.ts, src/Misc.ts, src/MoveTree.ts, src/__tests__/GoEngine_sgf.test.ts, src/__tests__/Misc.test.ts
Core of the PR is fixing SGF escaping issue:
https://github.com/online-go/online-go.com/issues/1547
The SGF changes were not tested, as the SGF is generated server side, but I think it is pretty safe, lints, etc were fine & I triple checked. 
Apart from that, various minor refactors around it were made:
- added tests for SGF escaping
- sgf now uses linear `string` concatenation (via `array.join`) instead of quadratic `txt += "...."`
- refactored coordinate string, to remove copy-paste & improve safety & consistency (moved to `GoMath`)
- the code was well tested, so pretty safe I hope
- README now has info about tests
=> Fix sgf escaping & minor refactor

src/GobanCore.ts, src/MoveTree.ts, src/__tests__/GoEngine_sgf.test.ts
This fixes the following issue https://github.com/online-go/online-go.com/issues/1932
**Problem TL;DR:** analyze state is local, on network loss & reconnect, it goes away, which hurts
**Fix summary:** check whether the new engine (/state) has any new info (== the new move tree is subset of the old one), if not, keep the old one.
**Previously**, each call of `load` (e.g. on disconnect / connect cycle) would re-initialize the `GoEngine` anew. This is a problem if the user was in analyze mode which is only stored locally, it would get overwritten on the `load`
**Now**, the `GobanCore.load` checks, and if the newly loaded information is only a subset of the current move tree (&& we are in analyze mode && few other checks), we do not update the engine & keep the old one.
**Caveat:**  we create …
=> Jm fix analyze on network fail

src/GobanCanvas.ts
Fixed #92.
This is the change suggested by @benjaminpjones  in #93 - the minimal change to deal with the specific pain point.
It does not attempt to make right-click consistent across modes, it just stops it placing a stone in play mode.
=> Prevent right-click from placing a stone in play-mode

jest.config.ts, src/GobanCanvas.ts, src/GobanCore.ts, src/__tests__/GobanCanvas.test.ts
See discussion on #97 for context
- Remove "edit" mode
- It was unclear what this mode was used for.  It seems similar to placing white or black stones in "analyze" mode, except the "game/move" message is emitted.  At any rate, neither of the other repos use this mode.
- Remove "setup" mode
- No logic associated with this mode. Likely some confusion with `PuzzlePlacementSetting.mode`.
- Add test for the label subtool (the test places one "triangle" label)
- Technically, this is not handled in `onTap()`, but we do need to make sure `onTap()` exits without unwanted side-effects
- Add a test for one click submit, mocking the socket
- I also added a type for `server_socket` in `GobanConfig`.  Does not appear to break the other repos.
- Delete a duplicate test - somehow I ended up with two …
=> Hodge-podge of small code health improvements

src/GoEngine.ts, src/GobanCanvas.ts, src/__tests__/GobanCanvas.test.ts
Now that this section is covered in tests, I figure a little refactoring is in order.
- cf600d4: add one more test to cover the ctrl-click case.  This passes before and after the refactor
- 04e40ee: Removes scoring_mode and ctrl/alt/metakey checks since onTap will never see these cases (see code snippet below)
- e1ef8d9: Remove the second socket message that gets sent when clicking a stone to remove it. 
- I tested this manually and removing this seems to make no difference to the end user.  At the very least, it is unclear what it is supposed to mean.
- Not only cleans up not network traffic, but also the code by reducing nesting.
----
The only place `onTap` is called is in `pointerUp()`.  This heavily simplified snippet should illustrate why `scoring_mode` and …
=> onTap: remove unnecessary stone removal/scoring_mode code

src/GoMath.ts, src/__tests__/GoMath.test.ts
Adds a function to get an `Array<JGOFMove>` from an OJE position (which is a move-sequence-string)
This is handy if you need to initailize a Goban from an OJE position :)
I put this into the `GoMath` file, because it seems to be `GoMath`.  I discovered I don't really know why tons of functions in there are inside the GoMath class.
I could't use my new function in the way that I wanted to do when it was in the class.
=> Oje sequence to moves

src/GoEngine.ts, src/GoMath.ts, src/ScoreEstimator.ts, src/__tests__/GoMath.test.ts, src/__tests__/GoMath_GoStoneGroup.test.ts
`GoMath` appears not to use this function, but rather implements [its own flood fill](https://github.com/online-go/goban/blob/a36c53c93ffdbc1f1d8452ba36e4ba68e87140eb/src/GoMath.ts#L53-L77).
Also, since the comment `/** Public for usage in GoStoneGroup */` is not accurate, I made these methods private.
=> Remove foreachNeighbor() as an argument to GoMath

package.json, src/GoEngine.ts, src/GoMath.ts, src/GoStoneGroup.ts, src/GoStoneGroups.ts, src/GobanCanvas.ts, src/GobanCore.ts, src/MoveTree.ts, src/ScoreEstimator.ts, src/__tests__/GoMath.test.ts, src/__tests__/GoMath_GoStoneGroup.test.ts, src/__tests__/GoMath_positionId.test.ts, src/__tests__/GobanCanvas.test.ts, src/goban.ts
This refactor makes most of the member function of the old `GoMath` class into plain exported functions, and factors the `GoMath` object out into a new class `GoStoneGroups` (who's only method is `forEachGroup`).
It means that clients of GoMath now have to do the GoMath function imports by refering to GoMath module specifically, either by named-symbol-import or `import * as GoMath from "goban/src/GoMath"`
The latter makes existing calls to GoMath methods work unchanged.
=> Factor `GoStoneGroups` out of `GoMath`

src/GoEngine.ts, src/TypedEventEmitter.ts
For testing, it would be helpful to have `goban.eventNames()` and `goban.listenerCount()`.  I looked at adding those methods similar to the existing ones, but I thought it might be good just to pull the interface from EventEmitter3 directly.  It looks like [they've had a d.ts file for many years now](https://github.com/primus/eventemitter3/issues/67#issuecomment-250670758).
The type interface for the generic arg is a bit different - the values are function signatures instead of a single data object.  This is more flexible, supporting multiple arguments, but OGS doesn't really make use of that, so I made a type transformer `LegacyEventsShim` to convert our existing event interfaces to something EventEmitter3 can consume.
=> Use EventEmitter3 types

jest.config.ts, src/__tests__/GoEngine_computeScore.test.ts, src/engine.ts, src/goban.ts, src/test_utils.ts
This adds coverage for "happy paths".  There are a few patches of code that are uncovered ([AGA scoring bug remediation](https://github.com/online-go/goban/blob/16481d6b1b678766d18c248c66f689e28a548e7e/src/GoEngine.ts#L1882-L1897) & some mostly dead code [1](https://github.com/online-go/goban/blob/16481d6b1b678766d18c248c66f689e28a548e7e/src/GoEngine.ts#L1830-L1838), [2](https://github.com/online-go/goban/blob/16481d6b1b678766d18c248c66f689e28a548e7e/src/GoEngine.ts#L1792-L1800)).
=> Add tests for computeScore()

src/GoStoneGroup.ts, src/GoStoneGroups.ts
Supercedes  #113 and #114
The internals of `GoStoneGroup` do not use the following fields:
- `probable_color`
- `dame`
- `is_probably_dead`
- `is_probably_dame`
- `adjacent_white`
- `adjacent_black`
Because the fields are public, it's a little difficult to verify they aren't used, but `GoStoneGroup` is only constructed in `GoStoneGroups` and `GoStoneGroups` is only constructed in two places ([GoEngine](https://github.com/online-go/goban/blob/16481d6b1b678766d18c248c66f689e28a548e7e/src/GoEngine.ts#L1810), [ScoreEstimator](https://github.com/online-go/goban/blob/b1313e44a143e5903f58699614d231ada6800d71/src/ScoreEstimator.ts#L830)). Both scopes are short and the type checker should catch any erroneously removed fields.
Tested: `yarn build-debug`, `yarn test`
=> Remove unused fields in GoStoneGroup.

src/GoEngine.ts
... clients shouldn't have to worry about what composite type this is, unless they really care.
=> Give `GoEngineConfig.moves` a specific type that is exported.

src/GobanSocket.ts
...remember that we changed it.
Not a functional bug, but now the behaviour is more as intended.
=> Don't keep reseting the ping interval to a custom value every time... 

src/GoEngine.ts, src/GobanCanvas.ts, src/ScoreEstimator.ts, src/__tests__/GobanCanvas.test.ts, src/__tests__/ScoreEstimator.test.ts
I've wanted to play with ScoreEstimator for a while, but there is a lot going on in there, and it's not easy to test due to external dependencies on OGSScoreEstimator (c++ WASM lib) and the remote AI scorer. I figured the best way to approach this is to clean it up as much as I can in one pass and manually test all changes together.  That said, let me know if there are commits that aren't desired, it shouldn't be too hard for me to remove them.
- Make score estimator more approachable so we can experiment:
- interest in a new scoring tool expressed [here](https://forums.online-go.com/t/counting-tool-instead-of-score-estimator/49528)
- I'd like to try a less aggressive metagroup algorithm (https://github.com/online-go/online-go.com/issues/1670)
- As a follow-up, I'd like to make the local …
=> Clean up ScoreEstimator.ts

.eslintrc.js, src/ScoreEstimator.ts, src/__tests__/ScoreEstimator.test.ts, src/local_estimators/__tests__/voronoi.test.ts, src/local_estimators/voronoi.ts, src/local_estimators/wasm_estimator.ts
This PR adds the ability to choose between the OGS WASM estimator and a ["Voronoi"](https://forums.online-go.com/t/weak-score-estimator-and-japanese-rules/41041/70) estimator... or even a user-defined function.
WASM is still the default, but one can change the estimator like so:
```
goban.set_local_scorer(goban.estimateScoreVoronoi);
```
This is very useful for testing, since it was difficult to load the `OGSScoreEstimator` module in the test environment or mock it.  This PR raises line coverage in ScoreEstimator.ts from 20% to 89%.
---
Incidentally, I believe the local scorer interface is compatible with [@sabaki/influence](https://npm.io/package/@sabaki/influence), though I haven't tested it:
```
const influence = require('@sabaki/influence');
goban.set_local_scorer(influence.areaMap); …
```
=> Choose Your Scorer

src/GoEngine.ts, src/GobanCore.ts, src/ScoreEstimator.ts, src/__tests__/GobanCanvas.test.ts
A few more cleanup opportunities that became apparent after spending more time with the ScoreEstimator code.
=> Score estimator more cleanup

jest.config.ts, src/__tests__/ScoreEstimator.test.ts
Coverage for the file is 91% and global coverage is now 60%.
The remaining 10% is mostly some unused functions in SEGroup which I think we can get rid of (#139).
=> Add ScoreEstimator tests and raise threshold

src/GoStoneGroup.ts, src/ScoreEstimator.ts, src/__tests__/ScoreEstimator.test.ts
With some minor additions, `GoStoneGroup` can completely replace the `SEGroup` in the score estimator.
=> Deprecate SEGroup

src/ScoreEstimator.ts, src/__tests__/ScoreEstimator.test.ts
This bug was introduced in d6194f4c46fdf90b8a12de091b038939230b8ca1 and caused captures to be multiplied by a factor of `height`.
https://forums.online-go.com/t/in-game-score-estimator-bugged/50046
---
Testing: I added a unit test based on [stone_defender's demo board](https://online-go.com/review/1190037).  8x8 instead of 20x20.
=> Fix ScoreEstimator bug for Japanese scoring

src/GoEngine.ts
This commit changes `GoEngine.computeScore()` to return `0` for `handicap` when it does not contribute to the score.  Indirectly, this changes the scoring summary in the web-client to not show the handicap in this case.
This fixes an inconsistency in the API/return, which forwarded to the web-client and caused user confusion.
Previously it was neither consistently equal to the handicap (see AGA) nor the handicap scoring bonus (see Japanese/Korean/New Zealand).
- For Chinese/Ing, it was both the handicap scoring bonus and the handicap, which happen to be equal.
- For AGA, it was the handicap scoring bonus, which is `handicap-1`.
- For Japanese/Korean/New Zealand, it was the handicap (scoring bonus is 0).
Now, for all rulesets, it's the handicap scoring bonus (if any).  For a client …
=> Set 'handicap' from GoEngine.computeScore to the handicap bonus

src/GobanCanvas.ts
This goes on top of #148 , after #150  is in  :)
If you don't like #148, you don't need this.
If you do like #148, then you should do this if you've done #150 :)
=> Add set last move opacity to goban canvas interface

src/GoEngine.ts
Based on <https://www.cs.cmu.edu/~wjh/go/rules/KSS.html>, white should get an N-point handicap bonus in handicap games.  This is not from the official documentation of the Ing rules, but was requested by the AGA president.
=> Add the area handicap scoring bonus in Ing rules

src/Goban/themes/rendered_stones.ts
The mutable variable for the clamshell lines isn't reset for each line. I couldn't check the fix locally - the page fails to load test.js after running `yarn run dev`.
The problem:
=> Fix values of paths for clamshell lines

jest.config.ts
I noticed on #167 the GobanSVG onTap tests were flaky due to timeout.  The SVG tests usually complete in <50ms, but one onTap test jumps over the 200ms threshold on occasion.
While the SVG tests run noticeably slower than Canvas tests (1-10ms vs 20-50ms on average), I wasn't able to determine whether there is a real perf issue.  At any rate, I think it's reasonable to increase the timeout parameter since Jest's default is a whopping 5s.
I stress tested with this command:
```
for i in {1..10}; do yarn test || {echo "Failed after $i attempts" && break}; done
```
10 runs is more than enough to trigger the timeout at 200 ms, but we get no timeouts at the 1s threshold.
We could alternatively increase timeout on a per-test basis.  This would be fine too IMO, just takes more thought about which …
=> Increase test timeout to 1s

engine/package.json, examples/main.tsx, package.json, src/Goban.styl, src/Goban/Goban.ts, src/Goban/InteractiveBase.ts, src/Goban/SVGRenderer.ts, src/Goban/themes/rendered_stones.ts, test/unit_tests/GobanSVG.test.ts
This patch contains a number of rendering optimizations for the SVG renderer
=> Svg optimizations

src/engine/formats/JGOF.ts, src/engine/protocol/ClientToServer.ts
[Based on this forum post](https://forums.online-go.com/t/revisiting-automatch-time-settings-data-backed-proposal-for-new-automatch-settings-on-ogs/52303?u=elforo)
This PR sets up for[ the automatch box changes](https://github.com/online-go/online-go.com/pull/2749)
These changes add a rapid time control speed.
This requires server changes for the auto-matching.
=> Adds a rapid speed

src/Goban/OGSConnectivity.ts, src/engine/GobanEngine.ts
Fixes #2791
-Add a case when game ends in a tie (returns `0` instead of a player number)
-updates `winner` interface prop with `tie` as an option
- should `winner` interface prop be number or string? Where would it be set to be a string? I only saw numbers returned (for player id) but not sure when a string is set. 
- I didn't see any jest tests for this. If we don't need it its fine, just want to make sure i'm not missing it somewhere.
=> Updated game sound logic for case when game ends in a Tie #2958

src/Goban/CanvasRenderer.ts, src/Goban/Goban.ts, src/Goban/SVGRenderer.ts, src/Goban/themes/GobanTheme.ts, src/Goban/themes/image_stones.ts
Adds support for selecting the style of shadow you want for your stones. Current options are none, low, mid, high, anime, and custom.
=> VIBE: Implement stone shadow themes

README.md, src/engine/GobanEngine.ts
Fox SGFs use a non-standard komi value, affecting the score estimation feature.
Also updated the README with how to use this with the new Vite/submodules setup (let me know if there's a better way to do this, as the approach I'm using is annoying. I much preferred the yarn link approach, but that's broken now).
Before:
After:
=> Handle Fox SGF komi value
